version: "3.8"

services:
  # Node.jsアプリケーションサービス
  app:
    build:
      context: ./
    ports:
      - "3000:8080"
    volumes:
      - ./src:/app
      - node_modules:/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongodb
    command: npm run dev

  # MongoDB サービス
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mydatabase

# 永続化ボリュームの定義
volumes:
  mongodb_data:
  node_modules:
